# download the Excel data from the DOC site

name: Download DOC testing data Excel data

on:
#  schedule:
#    - cron: "*/5 * * * *"
   workflow_dispatch

jobs:
  download_data:
     name: Download DOC testing excel
     runs-on: ubuntu-latest
     steps:
       - name: checkout repo
         uses: actions/checkout@v2

       - shell: bash
         run:  |
           d=`date | tr ' ' '_'`
           cd data/DOC_downloads
           curl -o PA-DOC-COVID-19-Testing_LATEST.xlsx https://www.cor.pa.gov/Documents/PA-DOC-COVID-19-Testing.xlsx

       - name: Commit files # transfer the new html files back into the repository
         run: |
           git config --local user.name "mbod"
           git add ./data/DOC_downloads
           git commit -m "add downloaded DOC data"
       - name: Push changes # push the output folder to your repo
         uses: ad-m/github-push-action@main
         with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            force: true




#       - name: Upload math result for job 1
#         uses: actions/upload-artifact@v2
#         with:
#           name: DOC-data
#           path: PA-DOC-COVID-19-Testing_LATEST.xlsx
